### ISSUE TITLE
1:1 relationship between a style guide rule and SwiftLint rule

### ISSUE THREAD

**Issue by swift-ortal** [airbnb/swift#21]
Each of our style guide rules is associated with 0 or more SwiftLint rules.

Take the example:

> Omit unnecessary parentheses. SwiftLint: [control_statement](), [empty_parentheses_with_trailing_closure](), [unneeded_parentheses_in_closure_argument]()

It's associated with 3 rules, but it's unclear if enabling all 3 of those captures all cases this rule encompasses.

If instead there was a 1:1 mapping between our style guide rules and SwiftLint rules, it would be more clear.

There are at least two solutions to achieve this goal:

1. Split big rules into smaller ones (e.g. omit unnecessary parentheses in control statement, omit unnecessary parentheses in trailing closures, omit unnecessary parentheses in closure arguments).
1. Submit PRs to SwiftLint that encapsulate our rule into one rule.

Regardless of which solution we choose, it could also simplify the style guide by having a beginning section with all the rules that one should enable on SwiftLint, followed by another section containing those rules that can't be linted for.

A few advantages:

- Makes it easier for the developer to remember which styles they must remember and enforce manually vs. those that will automatically be caught.
- Makes the style guide easier to parse since there will be less rules.
- Avoids redundancy or mismatches between our style guide and SwiftLint rules.

**Comment by fdiaz** [comment]
Just talked to @swift-ortal 

Closing!
