### ISSUE TITLE
Indentation Rule Conflicts with Xcode Indentation Behavior

### ISSUE THREAD

**Issue by brynbodayle** [airbnb/swift#25]
For this rule:

> Closure end braces should have the same indentation as the line with their opening brace. This makes it easier to follow control flow through closures.

https://github.com/airbnb/swift#closure-end-brace-indentation

It's in conflict with this guiding tenet:

> These rules should not fight Xcode's ^ + I indentation behavior.

Style guide example:

```
// RIGHT

match(pattern: pattern)
  .compactMap { range in
    return Command(string: contents, range: range)
  }
  .compactMap { command in
    return command.expand()
  }
```

Xcode indentation:

```
// RIGHT

match(pattern: pattern)
  .compactMap { range in
    return Command(string: contents, range: range)
  }
  .compactMap { command in
    return command.expand()
}
```

**Comment by calda** [comment]
Closing this one since it seems outdated -- Xcode indentation is quite a moving target 😅
