### ISSUE TITLE
Long function invocations should also break on each argument

### ISSUE THREAD

**Issue by fdiaz** [airbnb/swift#40]
This rule is missing autocorrect. Following [this PR](https://github.com/airbnb/swift/pull/35).

---

* <a id='long-function-invocation'></a>(<a href='#long-function-invocation'>link</a>) **[Long](https://github.com/airbnb/swift#column-width) function invocations should also break on each argument.** Put the closing parenthesis on the last line of the invocation. [![SwiftLint: multiline_arguments](https://img.shields.io/badge/SwiftLint-multiline__arguments-008489.svg)](https://github.com/realm/SwiftLint/blob/master/Rules.md#multiline-arguments) [![SwiftLint: vertical_parameter_alignment_on_call](https://img.shields.io/badge/SwiftLint-vertical__parameter__alignment__on__call-008489.svg)](https://github.com/realm/SwiftLint/blob/master/Rules.md#vertical-parameter-alignment-on-call)

  <details>

  ```swift
  universe.generateStars(
    at: location,
    count: 5,
    color: starColor,
    withAverageDistance: 4)

  universe.generate(
    5,
    .stars,
    at: location)
  ```

  </details>

**Comment by calda** [comment]
It looks like SwiftFormat's [`--wraparguments before-first`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#wraparguments) rule may work here

**Comment by bachand** [comment]
@calda good find. I think `--wraparguments before-first --closingparen same-line` would be perfect! I’d love to have this rule back in the style guide.

**Comment by fdiaz** [comment]
Added in https://github.com/airbnb/swift/pull/101
