### ISSUE TITLE
Multi-line arrays should have each bracket on a separate line

### ISSUE THREAD

**Issue by fdiaz** [airbnb/swift#42]
This rule is missing autocorrect. Following [this PR](https://github.com/airbnb/swift/pull/35).

---

* <a id='multi-line-array'></a>(<a href='#multi-line-array'>link</a>) **Multi-line arrays should have each bracket on a separate line.** Put the opening and closing brackets on separate lines from any of the elements of the array. Also add a trailing comma on the last element.

  <details>

  ```swift
  // WRONG
  let rowContent = [listingUrgencyDatesRowContent(),
                    listingUrgencyBookedRowContent(),
                    listingUrgencyBookedShortRowContent()]

  let rowContent = [
    listingUrgencyDatesRowContent(),
    listingUrgencyBookedRowContent(),
    listingUrgencyBookedShortRowContent()
  ]

  // RIGHT
  let rowContent = [
    listingUrgencyDatesRowContent(),
    listingUrgencyBookedRowContent(),
    listingUrgencyBookedShortRowContent(),
  ]
  ```

  </details>

**Comment by calda** [comment]
It looks like SwiftFormat's [`wrapArguments --wrapcollections before-first`](https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#wraparguments) may work here

**Comment by fdiaz** [comment]
Added in https://github.com/airbnb/swift/pull/101
