### ISSUE TITLE
Omit unnecessary type specifiers for closure parameters

### ISSUE THREAD

**Issue by fdiaz** [airbnb/swift#52]
This rule is missing autocorrect. Following [this PR](https://github.com/airbnb/swift/pull/35).

---

* <a id='omit-closure-parameters-unnecessary-types'></a>(<a href='#omit-closure-parameters-unnecessary-types'>link</a>) **Omit unnecessary type specifiers for closure parameters.**

  <details>

  ```swift
  // WRONG
  someAsyncThing() { (argument: Bool, argument2: Bool) -> Void in
    ...
  }

  // RIGHT
  someAsyncThing() { argument, argument2 in
    ...
  }
  ```

  </details>

**Comment by calda** [comment]
Closing since this has been open for three years. I like this one personally but I think its intractable to autocomplete (since removing these type specifiers could break the build in cases where they are the only canonical source of a declaration's type).
