### ISSUE TITLE
Each type in a file should be preceded by MARK

### ISSUE THREAD

**Issue by fdiaz** [airbnb/swift#54]
This rule is missing autocorrect. Following [this PR](https://github.com/airbnb/swift/pull/35).

---

* <a id='marks-for-types'></a>(<a href='#marks-for-types'>link</a>) **Each type in a file should be preceded by `// MARK: - TypeName`.** [![SwiftLint: mark](https://img.shields.io/badge/SwiftLint-mark-008489.svg)](https://github.com/realm/SwiftLint/blob/master/Rules.md#mark)

  <details>

  #### Why?
  The hyphen visually distinguishes types from sections within those types (described below).

  </details>

**Comment by calda** [comment]
Added in #107
