### ISSUE TITLE
Within each top-level section, place content in the following order

### ISSUE THREAD

**Issue by fdiaz** [airbnb/swift#60]
This rule is missing autocorrect. Following [this PR](https://github.com/airbnb/swift/pull/35).

---

* <a id='subsection-organization'></a>(<a href='#subsection-organization'>link</a>) **Within each top-level section, place content in the following order.** This allows a new reader of your code to more easily find what he or she is looking for.
  * Constants (e.g. `static let gravity: CGFloat = 9.8`)
  * Static properties (e.g. `static let sharedInstance = Account()`)
  * Instance properties
  * Static methods
  * Class methods
  * Instance methods

**Comment by calda** [comment]
Reintroduced in #102
