### ISSUE TITLE
Discourage `none` case in enums

### ISSUE THREAD

**Issue by swift-ortal** [airbnb/swift#85]
Consider the following contrived example:

```
enum RhymingWord: String {
  case cone
  case done
  case gone
  case none
  case zone
}

func rhymingWord(_ userInput: String) -> RhymingWord? {
  switch userInput {
  case "c": return .cone
  case "d": return .done
  case "g": return .gone
  case "n": return .none
  case "z": return .zone
  default: return nil
  }
}

assert(rhymingWord("c") == RhymingWord.cone) // passes
assert(rhymingWord("n") == RhymingWord.none) // fails
```

At first glance, it's not obvious why the first assertion passed but the second failed. 

Expressions such as `.cone` are automatically converted to their expanded form (e.g. `RhymingWord.cone`) by the compiler. With all values expanded, the snippet becomes:

```
  switch userInput {
  case "c": return RhymingWord.cone
  case "d": return RhymingWord.done
  case "g": return RhymingWord.gone
  case "n": return Optional.none
  case "z": return RhymingWord.zone
  default: return Optional.none
  }
```

It's now obvious as to why the assertion is failing: Any optional enum set to `.none` will expand to `Optional.none` as opposed to its other `none` cases (e.g. `RhymingWord.none` in this case). This can lead to difficult to debug errors in code. 

Proposal:

- **Never allow `none` as a case in an enum**.

Alternatives considered:

- **Prevent any enum with the `none` case as being optional**. (E.g. force all consumers to use `RhymingWord` instead of `RhymingWord?` because it already has a `none` representation.) Producers have no control as to how someone uses their data type (nor should they). Consumers should always be able to use a data type as an optional if it makes sense.
- **Always fully qualify the `.none` case in enums**. (E.g. use `case "n": return RhymingWord.none` above.) This will be hard for consumers to remember to fully qualify only these specific cases.

**Comment by erichoracek** [comment]
The Swift 5.1 compiler adds a warning for the ambiguous `none` case in this scenario and requires you to make it explicit by prepending the desired enum name e.g. `RhymingWord.none` or `Optional.none`, see https://www.hackingwithswift.com/articles/182/whats-new-in-swift-5-1 for details. As such I don't think this would be necessary as an additional rule—what do you think?
