### ISSUE TITLE
Use Camel Case uses type_name SwiftLint rule, which has other consequences.

### ISSUE THREAD

**Issue by dcramps** [airbnb/swift#93]
https://github.com/airbnb/swift#use-camel-case - Use PascalCase for type and protocol names, and lowerCamelCase for everything else.

From the SwiftLint rule's description:
"Type name should only contain alphanumeric characters, start with an uppercase character and span between 3 and 40 characters in length."

This is beyond what the rule this guide enforces states, and does not enforce camel case, e.g. on property names:

<img width="641" alt="Screen Shot 2019-11-12 at 9 43 46 AM" src="https://user-images.githubusercontent.com/643865/68686247-f37f5980-0530-11ea-8c92-aec371751336.png">

This (the pascal part for sure) could be re-written using a custom rule, but SwiftLint only exposes TypeKinds in `match_kinds` in custom rules, without any support for SwiftDeclarationKind. wtf.

**Comment by bachand** [comment]
Thanks for filing this.
