### ISSUE TITLE
Prefer AnyObject over class in protocol definitions

### ISSUE THREAD

**Issue by gsabran** [airbnb/swift#97]
[This accepted Swift proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0156-subclass-existentials.md#class-and-anyobject) that merges the concepts of `class` and `AnyObject` states that

> we suggest only keeping AnyObject around

We should update the guide to align with this evolution of Swift.

Popular linters such as Swift format and Swift lint already have rules for this:

https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#anyobjectprotocol

https://github.com/realm/SwiftLint/tree/master/Source/SwiftLintFramework/Rules/Lint

**Comment by fdiaz** [comment]
this sounds good to me

**Comment by bachand** [comment]
@gsabran could you put up a PR?

**Comment by calda** [comment]
#99
